{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.appcompat",
    "module": "appcompat-resources",
    "version": "1.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable-animated",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "appcompat-resources-1.4.2.aar",
          "url": "appcompat-resources-1.4.2.aar",
          "size": 67071,
          "sha512": "ce65a34dfbd7b10d43c1950b8addb9a0e187f51c6d92493d4b0fd3568c1672605ad109440134c345fa824a3ce3c6e5d1f54e0a24883c70bb28d3ad076df09a10",
          "sha256": "ca0778c8a8d5a71f738d81008285fac554df09b68890355f68173c3843e6153f",
          "sha1": "d4e27bd00b20f3991663f2c45f1185c1acdfd429",
          "md5": "98028da48a45e2da25d7519e4cbb6f50"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable-animated",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "appcompat-resources-1.4.2.aar",
          "url": "appcompat-resources-1.4.2.aar",
          "size": 67071,
          "sha512": "ce65a34dfbd7b10d43c1950b8addb9a0e187f51c6d92493d4b0fd3568c1672605ad109440134c345fa824a3ce3c6e5d1f54e0a24883c70bb28d3ad076df09a10",
          "sha256": "ca0778c8a8d5a71f738d81008285fac554df09b68890355f68173c3843e6153f",
          "sha1": "d4e27bd00b20f3991663f2c45f1185c1acdfd429",
          "md5": "98028da48a45e2da25d7519e4cbb6f50"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "appcompat-resources-1.4.2-sources.jar",
          "url": "appcompat-resources-1.4.2-sources.jar",
          "size": 40855,
          "sha512": "6dbc472b68da1cf1e7c08973d9f796881ca59ab21bc922580d3ca8b07b206a50e07d9751cfc802d580cff5d08aa2f7dd84061cd090397328d14f090d2bc184bf",
          "sha256": "014980c366a1755d486e4cde2ea616cc2074963c5f48ffcb01dee15dd5f9421d",
          "sha1": "8f78838745a125dea62514f7b4f70e8776a6244e",
          "md5": "4e8141afafcbf7ffe9e19ec02207f2e0"
        }
      ]
    }
  ]
}
